/* DSblock model generated by Dymola from Modelica model dde
 Dymola Version 2014 (32-bit), 2013-03-25 translated this at Thu May 08 13:40:17 2014

   */

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#include <moutil.c>
PreNonAliasDef(0)
PreNonAliasDef(1)
DYMOLA_STATIC const char*modelName="dde";
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=0;
#define QJacobianCGDef_ 1
DYMOLA_STATIC long QJacobianCG_[6]={2 , 2 , 1 , 3 , 1 , 2};
DYMOLA_STATIC long QJacobianGC_[7]={
1 , 1 , 0 , 0 , 2 , 2 , 0};
DYMOLA_STATIC double QJacobianCD_[4]={0  , 44 , 50 , 66};
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

BoundParameterSection
InitialSection
InitialSection
DefaultSection
InitializeData(0)
InitialSection
InitialSection
Init=false;InitializeData(2);Init=true;
EndInitialSection

OutputSection

DynamicsSection
F_[0] = delay(X_[0], DP_[0], 0);
helpvar[0] = delay(X_[1], DP_[1], 1);
F_[1] = F_[0]+helpvar[0];
F_[2] = X_[1];

AcceptedSection1

AcceptedSection2

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareParameter("a", "", 0, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("b", "", 1, 0.2, 0.0,0.0,0.0,0,560)
DeclareState("y1", "", 0, 1, 0.0,0.0,0.0,0,560)
DeclareDerivative("der(y1)", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("y2", "", 1, 1, 0.0,0.0,0.0,0,560)
DeclareDerivative("der(y2)", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("y3", "", 2, 1, 0.0,0.0,0.0,0,560)
DeclareDerivative("der(y3)", "", 0.0, 0.0,0.0,0.0,0,512)
EndNonAlias(0)
#define NX_    3
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    0
#define NP_    2
#define NPS_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ 726088941
#define NHash2_ 173410893
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    0
#define SizePre_ 0
#define SizeEq_ 0
#define SizeDelay_ 2
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 1
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double *time, double X_[], double XD_[], double U_[], 
double DP_[], long IP_[], Dymola_bool LP_[], double F_[], double Y_[], double W_[], double QZ_[], double duser_[], long iuser_[], void*cuser_[]) {
static Real initStore[1];
}
StartDataBlock
EndDataBlock
